version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: task-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0896
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/some_name/
      # - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
