apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
        - name: node-js
          image: abdulovdb/node-js
          resources:
            limits:
              memory: "356Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: node-js-service
spec:
  type: LoadBalancer
  selector:
    app: node-js
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
